#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a firefox desktop='^1'
bspc rule -a discord desktop='^2'
bspc rule -a URxvt desktop='^3'

feh --bg-scale ~/bg.png
redshift &
polybar -r example &

picom &

firefox &
discord &
alacritty &
setxkbmap hu
